print("*CONVERSACION-CAMBIO CLIMATICO*")
print("Carlos:")
print("Hace mucho calor")
print("Ruben:")
print("si, el cambio climatico")
print("Carlos:")
print("la sociedad genera muchos residuos que contaminan el medio ambiente")
print("Carlos:")
print("verdad, queda tomar consciencia acerca de los efectos que genera las misma")
