print("COMO BARRER UNA HABITACION")
print("***********************************************")
print("Barrer eficientemente")
print("1. Arrastra la cabeza de la escoba por el suelo con movimientos cortos y deliberados.")
print("2. Comienza en los bordes de la habitacien y trabaja hacia el centro.")
print("3. Haz una pausa de vez en cuando para limpiar la escoba. ")
print("4. Recoge la pila que has estado formando con una pala para deshacerte de ella.")
print("5. Usa la tecnica del puente levadizo para solucionar las leneas molestas dejadas por la pala.")
print("*************************************************************")
print("simplificar el Barrido")
print("1. Limetate a los suelos compactos.")
print("2. Despeja el erea de cualquier posible obstruccien. ")
print("3. Limpia los desechos hemedos antes de barrer.")
print("4. Escoge una escoba apropiada para el erea que vas a barrer. ")

